/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2017-03-29 05:30:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admins.activation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class companyActivate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write(" \r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("   position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section1  {\r\n");
      out.write("   padding-top: 50px;\r\n");
      out.write("   height: 770px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section2 {\r\n");
      out.write("   padding-top: 50px;\r\n");
      out.write("   height: 770px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section3 {\r\n");
      out.write("   padding-top: 50px;\r\n");
      out.write("   height: 770px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section41 {\r\n");
      out.write("   padding-top: 50px;\r\n");
      out.write("   height: 770px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section42 {\r\n");
      out.write("   padding-top: 50px;\r\n");
      out.write("   height: 770px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("}\r\n");
      out.write("#section43 {\r\n");
      out.write("   padding-top: 50px;\r\n");
      out.write("   height: 770px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   background-color: white; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"t_board mt20\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"board_list\" summary=\"예치금 이용내역\">\r\n");
      out.write("\t\t\t\t\t\t\t<caption>비활성화 기업리스트</caption>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"6%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"18%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"18%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"15%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"18%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"15%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t<input class=\"input-text\" name=\"s\" id=\"s\" placeholder=\"Enter Search keywords...\" type=\"text\" />\r\n");
      out.write("\t\t<input id=\"searchsubmit\" value=\"Search\" type=\"submit\" />\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<th>No</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t<th>회사이름</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>연락처</th>  \r\n");
      out.write("\t\t\t\t\t\t\t\t<th>이메일</th>   \r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t비활성화 시기\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t<th>활성화여부</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- btn -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- //btn -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("  <ul class=\"pagination\">\r\n");
      out.write("    <li><a href=\"#\">1</a></li>\r\n");
      out.write("    <li><a href=\"#\">2</a></li>\r\n");
      out.write("    <li><a href=\"#\">3</a></li>\r\n");
      out.write("    <li><a href=\"#\">4</a></li>\r\n");
      out.write("    <li><a href=\"#\">5</a></li>\r\n");
      out.write("    <li><a href=\"#\">6</a></li>\r\n");
      out.write("    <li><a href=\"#\">7</a></li>\r\n");
      out.write("    <li><a href=\"#\">8</a></li>\r\n");
      out.write("    <li><a href=\"#\">9</a></li>\r\n");
      out.write("    <li><a href=\"#\">10</a></li>\r\n");
      out.write("   \r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("   <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>    \r\n");
      out.write("     <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>    \r\n");
      out.write("     <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
